# Generated by Django 3.2.11 on 2022-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0002_salaryscale_yearofexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
