# Generated by Django 3.2.11 on 2022-02-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recuit', '0003_educationlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuit.educationlevel')),
                ('jobType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuit.jobtype')),
                ('salaryScale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuit.salaryscale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yearOfExp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recuit.yearofexp')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
