# Generated by Django 3.2.4 on 2022-03-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0007_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='educationLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.educationlevel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.jobtype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='salaryScale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.salaryscale'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='yearOfExp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.yearofexp'),
        ),
    ]
