# Generated by Django 3.2.4 on 2022-04-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0008_auto_20220323_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
    ]
