# Generated by Django 3.2.4 on 2022-04-05 09:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0009_auto_20220405_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='activities',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
