# Generated by Django 3.2.4 on 2022-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0010_auto_20220405_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upload',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
