# Generated by Django 3.2.4 on 2022-04-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0015_alter_userprofile_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='educationLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.educationlevel'),
        ),
        migrations.AddField(
            model_name='job',
            name='salaryScale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.salaryscale'),
        ),
        migrations.AddField(
            model_name='job',
            name='yearOfExp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.yearofexp'),
        ),
    ]
