# Generated by Django 3.2.11 on 2022-05-03 13:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recuit', '0018_job_my_state_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('GradeStep', models.CharField(max_length=50)),
                ('proposed', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('attachment', models.FileField(upload_to='')),
                ('hr', models.IntegerField(choices=[(1, 'Approved'), (0, 'Pending')], default=0)),
                ('cm', models.IntegerField(choices=[(1, 'Approved'), (0, 'Pending')], default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('contractType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.contracttype')),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salaryRange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recuit.salaryscale')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
