# Generated by Django 3.2.11 on 2022-05-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0021_alter_jobposition_requestedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobPosition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recuit.jobposition'),
            preserve_default=False,
        ),
    ]
