# Generated by Django 3.2.11 on 2022-07-06 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0023_biodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biodata',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
