# Generated by Django 3.2.11 on 2022-07-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0026_questions_qunheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recuit.qunheader'),
            preserve_default=False,
        ),
    ]
