# Generated by Django 3.2.11 on 2022-07-12 08:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0027_questions_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='qunheader',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='qunheader',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
