# Generated by Django 3.2.11 on 2022-07-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0028_auto_20220712_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['question']},
        ),
    ]
