# Generated by Django 3.2.11 on 2022-07-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0030_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='mark',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
