# Generated by Django 3.2.11 on 2022-07-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recuit', '0033_auto_20220715_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='mark',
            field=models.IntegerField(max_length=50),
        ),
    ]
